# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: windows-latest

strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install robotframework-seleniumlibrary
  displayName: 'Install dependencies'

- script: |
    robot --output output.xml --report report.html --log log.html test.robot
  continueOnError: true
  displayName: 'Run UI Tests'

# Optional: Publish the test report artifacts to Azure DevOps for viewing
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)
    ArtifactName: robot-reports
    publishLocation: 'Container'
  displayName: 'Publish Robot Framework Reports'

# Optional: Publish the HTML report as a pipeline artifact (so you can view the test report)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/report.html'
    ArtifactName: 'Test Report'
    publishLocation: 'Container'
  displayName: 'Publish Test Report'

