name: CI 3
 
on:
  # Trigger the workflow on push events for the "main" branch
  push:
    branches: [ "YOUR_BRANCH_HERE" ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ${{ matrix.os }}
 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [headlesschrome,headlessfirefox,safari]
        exclude:
          - os: ubuntu-latest
            browser: safari
          - os: windows-latest
            browser: safari
        include:
          - os: windows-latest
            browser: edge
 
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
 
      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12.2
 
      # Step 3: Install dependencies
      - name: Setup Workspace
        run: |
          pip install robotframework selenium robotframework-seleniumlibrary
 
      
      # Step 4: Run Robot Framework Tests
      - name: Run Tests
        run: |
          robot --outputdir $GITHUB_WORKSPACE/results -v BROWSER:${{matrix.browser}} test.robot
 
      # Step 5: Upload Test Results (Windows)
      - name: Upload Test Report (Windows)
        if: matrix.os == 'windows-latest' && (success() || failure())
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ matrix.os }}${{matrix.browser}}-rf-results
          path: D:\results\
 
      # Step 6: Upload Test Results (Linux/macOS)
      - name: Upload Test Report (Linux/macOS)
        if: matrix.os != 'windows-latest' && (success() || failure())
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ matrix.os }}${{matrix.browser}}-rf-results
          path: ./results/
 
      # Step 7: Set Robot Framework exit code
      - name: Set Robot Framework exit code
        run: echo "ROBOT_RC=$?" >> "$GITHUB_ENV"