name: Run Robot Framework Tests with Selenium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar Python
      - name: Set up Python $(matrix.python-version)
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Instalar dependências do Chrome (Chrome e ChromeDriver)
      - name: Install Chrome and dependencies
        run: |
          # Baixar e instalar o Google Chrome
          sudo apt-get update
          sudo apt-get install -y wget curl
          sudo apt-get install -y google-chrome-stable

          # Baixar e instalar o ChromeDriver
          CHROME_VERSION=$(google-chrome --version | sed 's/[^0-9]*\([0-9]*\.[0-9]*\.[0-9]*\)/\1/')
          DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # Instalar dependências do Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install robotframework selenium robotframework-seleniumlibrary

      # Executar os testes do Robot Framework
      - name: Run Robot Framework Tests
        run: |
          robot --output output.xml --report report.html --log log.html test.robot

      # Fazer upload dos relatórios como artefatos
      - name: Upload Robot Framework Reports
        uses: actions/upload-artifact@v3
        with:
          name: robot-reports
          path: |
            output.xml
            report.html
            log.html