name: Robot Framework Tests with ChromeDriver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
     runs-on: ${{ matrix.os }}
    
    strategy:
        
        matrix:
            os: [ubuntu-latest, windows-latest,macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Run Robot Framework tests
        env:
          DISPLAY: :99
          CHROME_BIN: /usr/bin/chromium-browser
          CHROME_DRIVER: /usr/bin/chromedriver
        run: |
          run: robot .  